on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip3 install .
        working-directory: ./python
      - run: |
          npm install
          npm run build
        working-directory: ./javascript
